image: python:3.8

stages:
  - test
  - lint
  - deploy

before_script:
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install

Unit Tests:
  stage: test
  script:
    - poetry run pytest

Python Code Lint:
  stage: test
  script:
    - poetry run black .

Deplot:
  stage: deploy
  script:
    - deploy_script  
